### ISSUE TITLE
CommandResult is not always the array we expect

### ISSUE THREAD

**Issue by swentel** [nostrver-se/nostr-php#18]
e.g.

["NOTICE","invalid: \"pubkey\" is required"]
So check that in Relay::send()

**Comment by swentel** [comment]
A success call crashes too with this one though, so let's check what exactly changed before #14

**Comment by swentel** [comment]
Ok, fixed the response in Relay, that was already broken, but let's make sure we don't fatal here and catch other responses from the relay too.

**Comment by Sebastix** [comment]
Closing this issue, see https://github.com/nostrver-se/nostr-php/pull/60
