### ISSUE TITLE
Seeking co-maintainers

### ISSUE THREAD

**Issue by swentel** [nostrver-se/nostr-php#32]
I simply don't have time anymore to extend this further.

If anyone wants to take over (I can transfer), or want access, let me know!

**Comment by Sebastix** [comment]
I've just shared it on SN: https://stacker.news/items/212095

**Comment by Sebastix** [comment]
@swentel Are you still around somewhere? =) I did some debugging tonight (besides some rewriting code for https://www.drupal.org/project/nostr_simple_publish) and also created a pull request with some typos I came along.

**Comment by Sebastix** [comment]
@swentel As I'm continueing developing some Drupal modules where this library is a dependency, I would like to apply as no one else has applied for it yet. I'm open to do this maintainership with others (so keep the quest open for new maintainers), as I'm not very expierenced with this kind of maintainership.

**Comment by swentel** [comment]
@Sebastix I've send an invite, you have access now! :)

**Comment by Sebastix** [comment]
@swentel Thank you very much, ready to give this repo some love ❤️ 🚀

**Comment by Sebastix** [comment]
@swentel How can the info be updated on https://packagist.org/packages/swentel/nostr-php or the releases be managed (such as creating a new release)?

**Comment by Sebastix** [comment]
Will close this issue as I'm now able to spent quite some time on maintaining and further development of this repo.
If you would collaborate, please send me a message or just sent some PRs!
